name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    # Checkout the repository with write permission to the gh-pages branch
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'refs/heads/gh-pages'
        token: ${{ secrets.GITHUB_TOKEN }}

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: project
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}